kanban
todo
    id1["Design API"]
    id2["Write tests"]
    id3["Update docs"]
in-progress
    id4["Implement auth"]
    id5["Fix login bug"]
review
    id6["Code review PR #42"]
done
    id7["Deploy v1.0"]
    id8["Setup CI pipeline"]
