timeline
    title Evolution of the Web
    section Early Web
        1991 : World Wide Web invented
             : First website at CERN
        1994 : Netscape Navigator
             : PHP 1.0 released
        1995 : JavaScript created
             : Apache HTTP Server
    section Web 2.0
        2004 : Facebook launched
             : Firefox 1.0
        2006 : Twitter launches
             : AWS S3 and EC2
        2008 : Chrome browser
             : V8 JavaScript engine
        2009 : Node.js created
    section Modern Era
        2013 : React released
        2015 : ES6 standard
        2016 : Progressive Web Apps
