timeline
    title Evolution of the Web
    section Early Web
        1991 : World Wide Web invented by Tim Berners-Lee
              : First website goes live at CERN
        1993 : Mosaic browser released
              : HTML 1.0 specification
        1994 : Netscape Navigator 1.0
              : W3C founded
        1995 : JavaScript created by Brendan Eich
              : PHP 1.0 released
              : Apache HTTP Server launched
    section Web 2.0 Era
        1998 : Google founded
              : CSS2 recommendation
        2001 : Wikipedia launched
        2004 : Gmail launched in beta
              : Facebook founded
              : Firefox 1.0 released
        2005 : YouTube launched
              : Ajax coined by Jesse James Garrett
        2006 : Twitter launches
              : AWS S3 and EC2 launch
    section Modern Web
        2008 : Chrome browser released
              : V8 JavaScript engine
        2009 : Node.js created by Ryan Dahl
              : HTML5 draft published
        2010 : Instagram launched
              : AngularJS released
        2013 : React released by Facebook
        2014 : HTTP/2 draft
              : Vue.js released
        2015 : ES6 / ECMAScript 2015
              : Edge browser released
        2016 : Progressive Web Apps specification
