//! Fuzz targets for the byte-in render/detect paths.
//!
//!   zig build fuzz          # smoke: run each target once
//!   zig build fuzz --fuzz   # coverage-guided fuzzing (Zig web UI)
//!
//! Each target feeds Smith-generated bytes to a public entry point and only
//! asserts the absence of crashes / UB (errors are expected and ignored).
const std = @import("std");
const pozeiden = @import("pozeiden");

/// Draw a byte string from `smith`, weighted toward printable ASCII (mermaid
/// source is mostly ASCII) with some whitespace and arbitrary bytes mixed in.
fn drawInput(smith: *std.testing.Smith, buf: []u8) []const u8 {
    @disableInstrumentation();
    const len = smith.sliceWeightedBytes(buf, &.{
        .rangeAtMost(u8, 0x00, 0xff, 1), // any byte
        .rangeAtMost(u8, 0x20, 0x7e, 6), // printable ASCII
        .rangeAtMost(u8, '\t', '\n', 2), // tab / newline
    });
    return buf[0..len];
}

test "fuzz_render" {
    try std.testing.fuzz({}, fuzzRender, .{});
}

fn fuzzRender(_: void, smith: *std.testing.Smith) anyerror!void {
    @disableInstrumentation();
    var buf: [8192]u8 = undefined;
    const input = drawInput(smith, &buf);
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    const svg = pozeiden.render(arena.allocator(), input) catch return;
    _ = svg;
}

test "fuzz_detect" {
    try std.testing.fuzz({}, fuzzDetect, .{});
}

fn fuzzDetect(_: void, smith: *std.testing.Smith) anyerror!void {
    @disableInstrumentation();
    var buf: [8192]u8 = undefined;
    _ = pozeiden.detectDiagramType(drawInput(smith, &buf));
}

test "fuzz_render_strict" {
    try std.testing.fuzz({}, fuzzRenderStrict, .{});
}

fn fuzzRenderStrict(_: void, smith: *std.testing.Smith) anyerror!void {
    @disableInstrumentation();
    var buf: [8192]u8 = undefined;
    const input = drawInput(smith, &buf);
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    const svg = pozeiden.renderWithOptions(arena.allocator(), input, .{ .strict = true }) catch return;
    _ = svg;
}
